# Generated by Django 2.2.8 on 2019-12-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('product_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_price', models.CharField(help_text='Price of product in cents', max_length=10)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_productpricedetails', to='products.Product')),
            ],
        ),
    ]
